Scraper:
  url: "https://www.bengans.com/en/artiklar/cd/index.html"
  category: "CD"
  price_min: 0.99
  price_max: 600.00
  batch_size: 96
Loader:
  filename: "fetched_products.csv"
  path: "bengans_scraper/load/data/"
BigQuery:
  project_id: "bengans-store"
  dataset_id: "bengans"
  table_id: "products"